version: '3.8'
services:

  postgres_db:
    image: postgres:13
    container_name: iot_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: *******
      POSTGRES_DB: iot_auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # The Warehouse (Document DB)
  mongo_db:
    image: mongo:latest
    container_name: iot_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

